Adding service tests
dvlopez9811/seminario-workshop-api-testing-js pull request #2
Opened 2020-02-15 16:55 UTC by dvlopez9811

2020-02-15 17:02 UTC, holgiosalos reviewed
Ademas de los comentarios que te hice, agrega una prueba para el metodo HEAD

El metodo HEAD consiste en solicitar los headers para cualquier verbo http, en ese caso, pueden utilizar cualquier api existente, es decir, pueden hacer un head a: https://httpbin.org/get
Y verificar que el response contiene los headers

2020-02-15 17:02 UTC, holgiosalos commented on test/MyFirstApiConsume.test.js
> +describe('First Api Tests', () => {
Dentro de la función de describe deben ir los it que tienes abajo. La razón de esto, es que un describe se utiliza como una definición de una suite (conjunto) de pruebas que tienen algo en común (probar la url https://httpbin.org/) y cada it corresponde a una prueba especifica.

2020-02-15 17:02 UTC, holgiosalos commented on test/MyFirstApiConsume.test.js
> +  expect(response.status).to.equal(statusCode.OK);
revisa si quizás puedes agregar un body al request hecho al PATCH y verificar dicho body en los expect. De manera similar a lo hecho en el GET

2020-02-15 17:02 UTC, holgiosalos commented on test/MyFirstApiConsume.test.js
> +  expect(response.status).to.equal(statusCode.OK);
revisa si quizás puedes agregar un body al request hecho al PUT y verificar dicho body en los expect. De manera similar a lo hecho en el GET

2020-02-15 17:02 UTC, holgiosalos commented on test/MyFirstApiConsume.test.js
> +  expect(response.status).to.equal(statusCode.OK);
revisa si quizás puedes agregar un body al request hecho al DELETE y verificar dicho body en los expect. De manera similar a lo hecho en el GET

2020-02-15 17:02 UTC, holgiosalos commented on test/MyFirstApiConsume.test.js
> +  const response = await agent.delete('https://httpbin.org/delete');
es mejor utilizar `agent.del(.....`

2020-02-21 13:33 UTC, holgiosalos requested changes

2020-02-21 13:33 UTC, holgiosalos commented on test/MyFirstApiConsume.test.js
> +  const response = await agent.patch('https://httpbin.org/patch').query(query);
el body en los metodos PATCH PUT y DELETE, se envia con el metodo **send**, en lugar de **query**

2020-02-21 13:33 UTC, holgiosalos commented on test/MyFirstApiConsume.test.js
> +  const response = await agent.put('https://httpbin.org/put').query(query);
el body en los metodos PATCH PUT y DELETE, se envia con el metodo **send**, en lugar de **query**

2020-02-28 13:21 UTC, renardete approved these changes

2020-02-28 13:21 UTC, renardete commented on .vscode/settings.json
> +}
EOF

2020-02-28 14:15 UTC, holgiosalos requested changes
Elimina el archivo test/.MyFirstApiConsume.test.js.swp y aplica los cambios de EOF.

2020-02-28 14:16 UTC, holgiosalos approved these changes

2020-03-13 16:56 UTC, merged